# Generated by Django 3.1.5 on 2021-01-24 10:33

import baseapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
                ('pre_content', models.CharField(max_length=255, null=True, verbose_name='Краткое содержание')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to=baseapp.models.get_image_name, verbose_name='Изображение 900х550')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to=baseapp.models.get_image_name, verbose_name='Изображение 900х537')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='baseapp.category', verbose_name='Категория')),
            ],
        ),
    ]
