# Generated by Django 3.1.7 on 2022-01-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_auto_20210124_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_keywords',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='meta name'),
        ),
    ]
