# Generated by Django 3.1.7 on 2022-01-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_auto_20220111_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='meta_keywords',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='meta keywords'),
        ),
    ]
