# Generated by Django 3.1.7 on 2022-01-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_auto_20220111_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='meta name')),
                ('meta_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='meta description')),
                ('meta_keywords', models.TextField(blank=True, max_length=1024, null=True, verbose_name='meta keywords')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
