# Generated by Django 3.1.7 on 2022-01-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='meta title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='meta title'),
        ),
    ]
