# Generated by Django 4.1.2 on 2024-10-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_alter_article_id_alter_category_id_alter_pages_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Адрес организации')),
            ],
            options={
                'verbose_name': 'Адрес организации',
                'verbose_name_plural': 'Адреса организации',
            },
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name': 'SEO', 'verbose_name_plural': 'SEO'},
        ),
    ]
