# Generated by Django 4.1.2 on 2024-10-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_companyaddress_alter_pages_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Адрес указывается без города', max_length=150, verbose_name='Адрес организации')),
                ('mobile_phone', models.CharField(help_text='Указывайте телефон начиная с 7', max_length=150, verbose_name='Мобильный телефон')),
                ('phone', models.CharField(help_text='Указывайте телефон начиная с 7', max_length=150, verbose_name='Телефон')),
                ('working_rules', models.CharField(help_text='Пон-Пят: 9:00 - 18:00', max_length=150, verbose_name='Режим работы')),
                ('telegram_name', models.CharField(max_length=150, verbose_name='Имя пользователя телеграм')),
            ],
            options={
                'verbose_name': 'Контактные данные организации',
                'verbose_name_plural': 'Контактные данные организации',
            },
        ),
        migrations.DeleteModel(
            name='CompanyAddress',
        ),
    ]
