# Generated by Django 4.1.2 on 2024-10-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_companycontactdata_delete_companyaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontactdata',
            name='email',
            field=models.CharField(default='', max_length=150, verbose_name='Email'),
        ),
    ]
