# Generated by Django 4.1.2 on 2024-10-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_companycontactdata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontactdata',
            name='email',
            field=models.CharField(max_length=150, verbose_name='Email'),
        ),
    ]
