# Generated by Django 4.1.2 on 2024-10-09 17:58

import baseapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0011_alter_companycontactdata_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание товара')),
                ('price_base', models.IntegerField(blank=True, null=True, verbose_name='Цена базовой версии')),
                ('price', models.IntegerField(verbose_name='Цена версии Проф')),
                ('image', models.ImageField(upload_to=baseapp.models.get_image_name, verbose_name='Изображение 900х550')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
