# Generated by Django 3.1.5 on 2021-01-25 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('full_name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Полное наименование')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Адрес e-mail')),
                ('address1', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адрес юридический')),
                ('address2', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адрес фактический')),
                ('phone1', models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон')),
                ('phone2', models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткая характеристика')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Наименование')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Адрес e-mail')),
                ('address1', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адрес юридический')),
                ('address2', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адрес фактический')),
                ('phone1', models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон')),
                ('phone2', models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.customer', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Сотрудник заказчика',
                'verbose_name_plural': 'Сотрудники заказчика',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Фамилия')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=1, verbose_name='Пол')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Адрес e-mail')),
                ('address1', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адрес по прописке')),
                ('address2', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адрес проживания')),
                ('phone1', models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон')),
                ('phone2', models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткая характеристика')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Физические лица',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('task_status', models.CharField(choices=[('A', 'Запланирована'), ('B', 'Выполняется'), ('C', 'Проверяется'), ('D', 'Выполнена')], default='A', max_length=1, verbose_name='Статус')),
                ('dead_line', models.DateField(blank=True, null=True, verbose_name='Исполнить до')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='crmapp.customer', verbose_name='Заказчик')),
                ('from_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_customer', to='crmapp.employee', verbose_name='От заказчика')),
                ('from_performer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_performer', to='crmapp.employee', verbose_name='От исполнителя')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performer', to='crmapp.customer', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.person', verbose_name='Физическое лицо'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='customer',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.person', verbose_name='Физическое лицо'),
        ),
    ]
