# Generated by Django 3.1.5 on 2021-01-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Адрес юридический'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Адрес фактический'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Краткая характеристика'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Адрес e-mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='kpp',
            field=models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone1',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Адрес юридический'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Адрес фактический'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Адрес e-mail'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone1',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Адрес по прописке'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Краткая характеристика'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Адрес e-mail'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone1',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Телефон'),
        ),
    ]
