# Generated by Django 3.1.5 on 2021-02-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_auto_20210125_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_performer',
            field=models.BooleanField(default=False, verbose_name='Исполнитель по умолчанию'),
        ),
    ]
