# Generated by Django 3.1.5 on 2021-02-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_customer_is_performer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Адрес юридический'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Адрес фактический'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Адрес e-mail'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone1',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Телефон'),
        ),
    ]
