# Generated by Django 3.1.5 on 2021-02-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0009_auto_20210219_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time_actual',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time_scheduled',
        ),
        migrations.AddField(
            model_name='task',
            name='time_actual_h',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Время выполнения, факт:'),
        ),
        migrations.AddField(
            model_name='task',
            name='time_actual_m',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Время выполнения, факт:'),
        ),
        migrations.AddField(
            model_name='task',
            name='time_scheduled_h',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Время выполнения, план:'),
        ),
        migrations.AddField(
            model_name='task',
            name='time_scheduled_m',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Время выполнения, план:'),
        ),
    ]
