# Generated by Django 3.1.5 on 2021-02-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0010_auto_20210219_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_actual_h',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Время выполнения, факт:'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_actual_m',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Время выполнения, факт:'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_scheduled_h',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Время выполнения, план:'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_scheduled_m',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Время выполнения, план:'),
        ),
    ]
