# Generated by Django 3.1.5 on 2021-02-22 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0011_auto_20210222_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='from_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_customer', to='crmapp.employee', verbose_name='От заказчика'),
        ),
        migrations.AlterField(
            model_name='task',
            name='from_performer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_performer', to='crmapp.employee', verbose_name='От исполнителя'),
        ),
    ]
