# Generated by Django 3.1.5 on 2021-03-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0013_auto_20210228_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_of_completion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата исполнения'),
        ),
    ]
