# Generated by Django 3.1.5 on 2021-03-13 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crmapp', '0014_task_date_of_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('task_status', models.CharField(choices=[('A', 'Запланирована'), ('B', 'Выполняется'), ('C', 'Проверяется'), ('D', 'Выполнена')], default='A', max_length=1, verbose_name='Статус')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task', to='crmapp.task', verbose_name='Задача')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Журнал изменения статусов',
                'ordering': ['date'],
            },
        ),
    ]
