# Generated by Django 3.1.7 on 2021-07-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0019_auto_20210615_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='for_payment',
            field=models.BooleanField(default=False, verbose_name='Оплачивается'),
        ),
    ]
