# Generated by Django 3.1.7 on 2021-07-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0020_task_for_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Телефон 2'),
        ),
    ]
