# Generated by Django 3.1.7 on 2021-07-13 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0023_auto_20210713_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='crmapp.customer', verbose_name='Заказчик'),
        ),
    ]
