# Generated by Django 3.1.7 on 2021-07-13 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0024_auto_20210713_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_as',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('full_name', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Полное наименование')),
                ('inn', models.CharField(blank=True, default='', max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, default='', max_length=9, verbose_name='КПП')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Адрес e-mail')),
                ('address1', models.CharField(blank=True, default='', max_length=1024, verbose_name='Адрес юридический')),
                ('address2', models.CharField(blank=True, default='', max_length=1024, verbose_name='Адрес фактический')),
                ('phone1', models.CharField(blank=True, default='', max_length=25, verbose_name='Телефон')),
                ('phone2', models.CharField(blank=True, default='', max_length=25, verbose_name='Телефон 2')),
                ('description', models.TextField(blank=True, default='', verbose_name='Краткая характеристика')),
                ('is_performer', models.BooleanField(default=False, verbose_name='Исполнитель по умолчанию')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.person', verbose_name='Физическое лицо')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'ordering': ['name'],
            },
        ),
    ]
