# Generated by Django 3.1.7 on 2021-07-13 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0025_customer_as'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_as',
        ),
    ]
