# Generated by Django 3.1.7 on 2021-07-13 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0026_delete_customer_as'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='for_payment',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='task',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='crmapp.customer', verbose_name='Заказчик'),
        ),
    ]
