# Generated by Django 3.1.7 on 2021-07-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0027_auto_20210713_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='for_payment',
            field=models.BooleanField(default=False, verbose_name='Оплачивается'),
        ),
    ]
