# Generated by Django 3.1.7 on 2022-10-10 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crmapp', '0028_task_for_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FN_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='Тип накопителя')),
                ('validity', models.CharField(max_length=16, verbose_name='Срок действия')),
            ],
        ),
        migrations.CreateModel(
            name='Point_of_sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='Адрес точки продаж')),
                ('postcode', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Индекс')),
                ('region', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Регион')),
                ('area', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Район')),
                ('city', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Город')),
                ('locality', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Населенный пункт')),
                ('street', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Дом')),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.customer', verbose_name='Заказчик')),
            ],
        ),
        migrations.CreateModel(
            name='KKT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rn_kkt', models.CharField(max_length=16, verbose_name='Регистрационный номер ККТ')),
                ('mn_kkt', models.CharField(max_length=14, verbose_name='Заводской номер ККТ')),
                ('model_kkt', models.CharField(max_length=16, verbose_name='Модель ККТ')),
                ('fiscalization_date', models.DateField(blank=True, null=True, verbose_name='Дата фискализации')),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.customer', verbose_name='Заказчик')),
                ('point_of_sale', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='FN_accounting.point_of_sale', verbose_name='Точка продаж')),
            ],
        ),
        migrations.CreateModel(
            name='FN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn_model', models.CharField(max_length=16, verbose_name='Модель накопителя')),
                ('fn_mn', models.CharField(max_length=16, verbose_name='Заводской номер ФН')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Дата фискализации')),
                ('fn_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='FN_accounting.fn_type', verbose_name='Тип ФН')),
            ],
        ),
    ]
