# Generated by Django 3.1.7 on 2022-10-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FN_accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point_of_sale',
            name='area',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='point_of_sale',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='point_of_sale',
            name='house',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='point_of_sale',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='point_of_sale',
            name='region',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='point_of_sale',
            name='street',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='point_of_sale',
            name='title',
            field=models.CharField(max_length=512, verbose_name='Адрес точки продаж'),
        ),
    ]
