# Generated by Django 3.1.7 on 2022-10-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FN_accounting', '0003_auto_20221010_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fn',
            name='uid',
            field=models.SlugField(max_length=36, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='fn_type',
            name='uid',
            field=models.SlugField(max_length=36, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='kkt',
            name='uid',
            field=models.SlugField(max_length=36, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='point_of_sale',
            name='uid',
            field=models.SlugField(max_length=36, unique=True, verbose_name='Идентификатор'),
        ),
    ]
