# Generated by Django 4.1.2 on 2022-10-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FN_accounting', '0004_auto_20221010_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fn',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fn_type',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kkt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='point_of_sale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
