# Generated by Django 4.1.2 on 2022-10-10 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FN_accounting', '0005_alter_fn_id_alter_fn_type_id_alter_kkt_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kkt',
            name='fn',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='FN_accounting.fn', verbose_name='Фискальный накопитель'),
        ),
        migrations.AlterField(
            model_name='fn_type',
            name='title',
            field=models.CharField(max_length=16, verbose_name='Наименование'),
        ),
    ]
