# Generated by Django 4.1.2 on 2022-10-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FN_accounting', '0006_kkt_fn_alter_fn_type_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fn',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
    ]
