# Generated by Django 4.1.2 on 2022-10-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FN_accounting', '0007_fn_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fn',
            name='uid',
            field=models.SlugField(blank=True, max_length=36, null=True, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='fn_type',
            name='uid',
            field=models.SlugField(blank=True, max_length=36, null=True, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='kkt',
            name='uid',
            field=models.SlugField(blank=True, max_length=36, null=True, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='point_of_sale',
            name='uid',
            field=models.SlugField(blank=True, max_length=36, null=True, unique=True, verbose_name='Идентификатор'),
        ),
    ]
