# Generated by Django 4.1.2 on 2022-10-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FN_accounting', '0008_alter_fn_uid_alter_fn_type_uid_alter_kkt_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fn_type',
            name='validity',
            field=models.IntegerField(verbose_name='Срок действия'),
        ),
    ]
