# Generated by Django 4.1.2 on 2023-07-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FN_accounting', '0009_alter_fn_type_validity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fn',
            options={'verbose_name': 'Фискальный накопитель', 'verbose_name_plural': 'Фискальные накопители'},
        ),
        migrations.AlterModelOptions(
            name='fn_type',
            options={'verbose_name': 'Тип фискального накопителя', 'verbose_name_plural': 'Типы фискальных накопителей'},
        ),
        migrations.AlterModelOptions(
            name='kkt',
            options={'verbose_name': 'ККТ', 'verbose_name_plural': 'ККТ'},
        ),
        migrations.AlterModelOptions(
            name='point_of_sale',
            options={'verbose_name': 'Точка продаж', 'verbose_name_plural': 'Точки продаж'},
        ),
        migrations.RemoveField(
            model_name='point_of_sale',
            name='customer',
        ),
    ]
