# Generated by Django 4.1.2 on 2023-09-13 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0029_alter_customer_id_alter_employee_id_alter_person_id_and_more'),
        ('FN_accounting', '0010_alter_fn_options_alter_fn_type_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_of_sale',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.customer', verbose_name='Заказчик'),
        ),
    ]
