# Generated by Django 3.1.7 on 2021-07-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecord',
            name='section',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='knowledge_baseapp.section', verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='record',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='knowledge_baseapp.section', verbose_name='Раздел'),
        ),
    ]
