# Generated by Django 3.1.6 on 2021-07-13 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_baseapp', '0002_auto_20210706_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecord',
            name='section',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='knowledge_baseapp.section', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='record',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge_baseapp.section', verbose_name='Раздел'),
        ),
    ]
