# Generated by Django 3.1.7 on 2021-08-06 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0028_task_for_payment'),
        ('knowledge_baseapp', '0003_auto_20210713_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='record',
            name='section',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='knowledge_baseapp.section', verbose_name='Раздел'),
        ),
    ]
