# Generated by Django 3.1.7 on 2022-10-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_baseapp', '0004_auto_20210806_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalrecord',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Запись', 'verbose_name_plural': 'historical Записи'},
        ),
        migrations.AlterModelOptions(
            name='historicalsection',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Раздел', 'verbose_name_plural': 'historical Разделы'},
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsection',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
